server:
  port: 8888
  servlet:
    session:
      # session超时时间，单位为秒
      timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://47.107.73.52/moli?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: moli520
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: FebsHikariCP

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security: info
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
moli:
  showsql: true
  security:
    # 登录路径
    login-url: /login
    # 登出路径
    logout-url: /logout
    # 首页路径
    index-url: /index
    # 免认证静态资源路径
    anon-resources-url: /css/**,/js/**,/fonts/**,/img/**
    # 记住我有效时间，单位为秒
    remember-me-timeout: 3600
    # 验证码相关配置
    code:
      # 图形验证码相关配置
      image:
        # 图形验证码由字符位数
        length: 4
        # 图形验证码图片长度，单位 px
        width: 148
        # 图形验证码高度，单位 px
        height: 36
        # 图形验证码失效时间
        expire-in: 60
        # 以下资源需要验证图形验证码
        url: /test/img/code
        # 生成图形验证码的请求 url
        create-url: /image/code
        # 对应图形验证码登录页面 form表单的 action属性
        login-processing-url: /form/login

      # 短信验证码相关配置
      sms:
        # 短信验证码字符位数
        length: 4
        # 短信验证码的有效时间，单位为秒
        expire-in: 120
        # 以下资源需要短信验证码验证
        url: /mobile/bind,/mobile/unbind,/test/sms/code
        # 生成短信验证码的请求 url
        create-url: /sms/code
        # 对应短信验证码登录页面 form表单的 action属性
        login-processing-url: /mobile/login


